baseURL = "http://msoto.github.io/"
languageCode = "en-us"
title = "MoiSoto's Dev Corner"
theme = "soho"

enableInlineShortcodes = true

summarylength = 10
enableEmoji = true

[params]
author = "Moises Soto"
description = "Hosted by GitHub"

## Set one of:
#gravatar = "msoto@example.com"
#profilePicture = "images/profile.png"
profilePicture = "images/profilepic.jpg"

copyright = "Moises Soto"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
# themeColor = "#fc2803"

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/blog.css"]
customJs = ["js/blog.js"]

  ## Set as many as you want.
  #[[params.socialIcons]]
  #icon = "fa-linkedin"
  #title = "Linkedin"
  #url = "#"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/moisoto"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/moisoto"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 300
  url = "/about/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4
